STUDY_NAME : "competencia-02-study-1-0"

BUCKET_NAME: "/home/tomas/Desktop/maestria/dm-eyf/competencia-02-bucket"

competencia02:
    DATA_PATH: "/home/tomas/Desktop/maestria/dm-eyf/competencia.csv"
    SEMILLA: [811157, 502717, 782911, 464939, 213713]
    MES_TRAIN: [202101, 202102, 202103]
    MES_VALIDACION: 202103
    MES_TEST: 202104
    FINAL_TRAIN: [202101, 202102, 202103, 202104]
    FINAL_PREDIC: 202106
    GANANCIA_ACIERTO: 780000
    COSTO_ESTIMULO: 20000