STUDY_NAME : "competencia-02-study-1-0"

BUCKET_NAME: "/home/tomas/Desktop/maestria/dm-eyf/repo-propio/bucket"

DATASET_CRUDO_PATH: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/data/competencia_01_crudo.csv"
DATASET_TERNARIA_PATH: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/data/competencia_01.csv"
DATASET_FE_PATH: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/data/competencia_01_fe.csv"
DICCIONARIO_DATOS: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/data/diccionario_datos.csv"

competencia02:
    DATA_PATH: "/home/tomas/Desktop/maestria/dm-eyf/repo-propio/data/competencia_01_crudo.csv"
    TABLE_NAME: "competencia_01_fe"
    SEMILLA: [50,100,150,400,700,1000,1500,2000,3000]
    MES_TRAIN: [202101, 202102, 202103]
    MES_VALIDACION: 202103
    MES_TEST: 202104
    FINAL_TRAIN: [202101, 202102, 202103, 202104]
    FINAL_PREDIC: 202106
    GANANCIA_ACIERTO: 780000
    COSTO_ESTIMULO: 20000