STUDY_NAME : "competencia-02-study-1-0"

BUCKET: "/home/tomas/Desktop/maestria/dm-eyf/data/"

DATASETS_PATH: "/home/tomas/Desktop/maestria/dm-eyf/data/"

DATASET_CRUDO_FILE: "competencia_01_crudo.csv"
DATASET_TERNARIA_FILE: "competencia_01.csv"
DATASET_FE_FILE: "competencia_01_fe.csv"
DICCIONARIO_DATOS: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/dmeyf2025/competencia-02/diccionario_datos.csv"

MODELOS_PATH : "modelos/"

TABLE_NAME: "competencia_01_fe"
SEMILLA: [50,100,150,400,700,1000,1500,2000,3000]
MES_TRAIN: [202101, 202102, 202103]
MES_VALIDACION: 202103
MES_TEST: 202104
FINAL_TRAIN: [202101, 202102, 202103, 202104]
FINAL_PREDICT: 202106
GANANCIA_ACIERTO: 780000
COSTO_ESTIMULO: 20000
THRESHOLD : 0.15
SUBMISSION_NUMBER : 1

TRAIN_TEST_MODELS : False