STUDY_NAME : "competencia-02-study-1-0"

BUCKET: "/home/tomas/Desktop/maestria/dm-eyf/data/"

DATASET_PATH: "/home/tomas/Desktop/maestria/dm-eyf/data/"

DATASET_CRUDO_PATH: "competencia_01_crudo.csv"
DATASET_TERNARIA_PATH: "competencia_01.csv"

DICCIONARIO_DATOS: "/home/tomas/Desktop/maestria/dm-eyf/repo_propio/dmeyf2025/competencia-02/diccionario_datos.csv"
MODELOS_PATH = "modelos/"

competencia02:
    DATASET_FE_PATH: "competencia_01_fe.csv"
    TABLE_NAME: "competencia_01_fe"
    SEMILLA: [50,100,150,400,700,1000,1500,2000,3000]
    MES_TRAIN: [202101, 202102, 202103]
    MES_VALIDACION: 202103
    MES_TEST: 202104
    FINAL_TRAIN: [202101, 202102, 202103, 202104]
    FINAL_PREDIC: 202106
    GANANCIA_ACIERTO: 780000
    COSTO_ESTIMULO: 20000